# -*- coding: utf-8 -*-
"""deep_learning_celsius_fahrenheit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPfDqU25-sbKDT_fczyBHa6XNbDsTvfH

# Relatório de Aula Prática — Deep Learning
## Classificação de Temperatura com Redes Neurais (TensorFlow/Keras)
**Aluno:** Kevin Richardson dos Santos Meneses  
**Disciplina:** Redes Neurais e Deep Learning  
**Ambiente:** Google Colaboratory

## 1. Importação de Bibliotecas e Definição dos Dados
Importamos o TensorFlow, NumPy e matplotlib. Os dados de treinamento são 7 pares de temperaturas conhecidas em Celsius e seus equivalentes em Fahrenheit. O modelo deverá aprender a relação F = C × 1,8 + 32 sem que a fórmula seja fornecida explicitamente.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Dados de treinamento
celsius    = np.array([-40, -10, 0, 8, 15, 22, 38], dtype=float)
fahrenheit = np.array([-40,  14, 32, 46.4, 59, 71.6, 100], dtype=float)

print(f'Celsius:    {celsius}')
print(f'Fahrenheit: {fahrenheit}')
print(f'Número de amostras de treinamento: {len(celsius)}')

"""## 2. Construção e Compilação do Modelo
O modelo utiliza a API Sequential do Keras com uma única camada Dense de 1 neurônio. Isso é suficiente para aprender relações lineares. O otimizador Adam ajusta os pesos iterativamente minimizando o erro absoluto médio (MAE).
"""

# Construção do modelo
modelo = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
])

# Compilação
modelo.compile(
    optimizer='adam',
    loss='mean_absolute_error'
)

modelo.summary()

"""## 3. Treinamento do Modelo
O modelo é treinado por 500 épocas. A cada época, os pesos são ajustados para reduzir a perda. O histórico de treinamento é armazenado para análise posterior.
"""

print('Iniciando treinamento...')
historico = modelo.fit(
    celsius,
    fahrenheit,
    epochs=500,
    verbose=1
)
print('\nTreinamento concluído!')
print(f'Loss final: {historico.history["loss"][-1]:.6f}')

"""## 4. Gráfico de Loss por Época
O gráfico a seguir mostra a evolução da perda (MAE) ao longo das 500 épocas de treinamento. Uma curva descendente acentuada no início, seguida de estabilização próxima de zero, indica que o modelo convergiu com sucesso.
"""

plt.figure(figsize=(10, 4))
plt.plot(historico.history['loss'], color='steelblue', linewidth=2)
plt.title('Perda (Loss) por Época — Treinamento do Modelo', fontsize=13, fontweight='bold')
plt.xlabel('Época', fontsize=11)
plt.ylabel('Loss (MAE)', fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""## 5. Tabela Comparativa — Modelo vs. Fórmula Real
Para avaliar a qualidade das predições, 10 temperaturas em Celsius não presentes no conjunto de treinamento foram testadas. Os resultados do modelo são comparados com o valor real calculado pela fórmula F = C × 1,8 + 32.
"""

testes = [-50, -20, 5, 10, 25, 30, 40, 50, 75, 100]

print(f"{'Celsius':>8} | {'Modelo (°F)':>12} | {'Fórmula (°F)':>13} | {'Erro Abs.':>10}")
print('-' * 52)

for c in testes:
    pred  = modelo.predict(np.array([[c]], dtype=np.float32), verbose=0)[0][0]
    real  = c * 1.8 + 32
    erro  = abs(pred - real)
    print(f"{c:>8} | {pred:>12.2f} | {real:>13.2f} | {erro:>10.4f}")

"""## 6. Pesos Aprendidos pelo Modelo
Os pesos da camada Dense revelam o que o modelo aprendeu. Em uma relação linear perfeita, esperamos que o peso (w) se aproxime de 1,8 e o bias (b) de 32, que são exatamente os coeficientes da fórmula F = C × 1,8 + 32.
"""

peso, bias = modelo.layers[0].get_weights()
print(f'Peso aprendido (w): {peso[0][0]:.4f}  (esperado: 1.8)')
print(f'Bias aprendido  (b): {bias[0]:.4f}  (esperado: 32.0)')